lines = {
    '00': 'nollanollanollakauttaviis.mp3',
    '0' : 'nollakauttaviis.mp3',
    '1' : 'ykskauttaviis.mp3',
    '2' : 'kakskauttaviis.mp3',
    '3' : 'kolmekauttaviispisteviis.mp3',
    '4' : 'neljakauttaviis.mp3',
    '5' : 'viiskauttaviis.mp3' ,
    'aamua' : 'aamua.mp3' ,
    'iltaa' : 'iltaa.mp3' ,
    'costarica' : 'costarica.mp3' ,
    'aika' : 'einoinnopeestivoiaikamenna.mp3' ,
    'es' : 'es.mp3' ,
    'gm' : 'goodmorning.mp3' ,
    'harmittaa' : 'harmittaamutteiharmita.mp3' ,
    'jaksa' : 'joseijaksanikoittakaavaajaksaa.mp3' ,
    'aamulehti' : 'juodaaamulehtee.mp3' ,
    'juustoensin' : 'juustoensinkunleipa.mp3' ,
    'kahvia' : 'kahvianaamarii.mp3' ,
    'kello' : 'kuntatavideookatsot.mp3' ,
    'lohi' : 'lohionkikala.mp3' ,
    'töihin' : 'meetoihin.mp3' ,
    'muurahaiset' : 'muurahaisetpaallekkain.mp3' ,
    'tunnelmiin' : 'naihinkuviin.mp3' ,
    'on' : 'on.mp3' ,
    'banjot' : 'paskahaiseejabanjotsoi.mp3' ,
    'sakset' : 'saksetmikrossa.mp3' ,
    'saturday' : 'saturdayandsunday.mp3' ,
    'tunteisiin' : 'tunteisiinsisimpaan.mp3' ,
    'muistopäivä' : 'vainajienmuistopaiva.mp3' ,
    'voivoi' : 'voivoivoivoi.mp3',
    'nyrkki' : 'nyrkki.mp3',
    'kaksitablettia' : 'kaksitablettia.mp3',
    'kala ' : 'kalaseinaan.mp3',
    'kesatyot' : 'kesatyot.mp3',
    'loma' : 'lomaviisaudet.mp3',
    'makarooni' : 'makarooniloota.mp3',
    'viiskauttaviis' : 'melkeinviiskauttaviis.mp3',
    'viikko' : 'pitkajaraskasviikko.mp3',
    'ruokailu' : 'ruokailen.mp3',
    'viikko' : ''
}

