lines = {
    '00': r'\nollanollanollakauttaviis.mp3',
    '0' : r'\nollakauttaviis.mp3',
    '1' : r'\ykskauttaviis.mp3',
    '2' : r'\kakskauttaviis.mp3',
    '3' : r'\kolmekauttaviispisteviis.mp3',
    '4' : r'\neljakauttaviis.mp3',
    '5' : r'\viiskauttaviis.mp3' ,
    'aamua' : r'\aamua.mp3' ,
    'iltaa' : r'\iltaa.mp3' ,
    'costarica' : r'\costarica.mp3' ,
    'aika' : r'\einoinnopeestivoiaikamenna.mp3' ,
    'es' : r'\es.mp3' ,
    'gm' : r'\good morning.mp3' ,
    'harmittaa' : r'\harmittaamutteiharmita.mp3' ,
    'jaksa' : r'\joseijaksanikoittakaavaajaksaa.mp3' ,
    'aamulehti' : r'\juodaaamulehtee.mp3' ,
    'juustoensin' : r'\juustoensinkunleipa.mp3' ,
    'kahvia' : r'\kahvianaamarii.mp3' ,
    'kello' : r'\kuntatavideookatsot.mp3' ,
    'lohi' : r'\lohionkikala.mp3' ,
    'töihin' : r'\meetoihin.mp3' ,
    'muurahaiset' : r'\muurahaisetpaallekkain.mp3' ,
    'tunnelmiin' : r'\naihinkuviin.mp3' ,
    'on' : r'\on.mp3' ,
    'banjot' : r'\paskahaiseejabanjotsoi.mp3' ,
    'sakset' : r'\saksetmikrossa.mp3' ,
    'saturday' : r'\saturdayandsunday.mp3' ,
    'tunteisiin' : r'\tunteisiinsisimpaan.mp3' ,
    'muistopäivä' : r'\vainajienmuistopaiva.mp3' ,
    'voivoi' : r'\voivoivoivoi.mp3',
    'nyrkki' : r'\nyrkki.mp3'
}

